enemy_color: red
bullet_speed: 23.0
serial:
  enable: true
  device_name: /dev/ttyACM0 
  baud_rate: 115200
  char_size: 8
  read_buf_size: 4096

camera: ${ROOT_DIR}/config/camera.yaml

auto_exposure:
  enable: true
  target_brightness: 25.0
  tolerance: 3.0
  step_gain: 15.0
  decay_step: 1.0
  exposure_min: 100.0
  exposure_max: 3500.0
  control_interval_ms: 300


armor_detector:
  armor_infer:
    model_type: tup
    conf_threshold: 0.2
  net_detector:
    backend: tensorrt
    openvino:
      model_path: ${ROOT_DIR}/model/opt-1208-001.onnx
      device_name: "CPU"
      perf_mode: "CUMULATIVE_THROUGHPUT"
      # priority: "MEDIUM"
      scheduling_core_type: "PCORE_ONLY"
      model_distribution_policy: "TENSOR_PARALLEL"
      execution_mode: "PERFORMANCE"
    tensorrt:
      model_path: ${ROOT_DIR}/model/opt-1208-001.onnx
      copy_context_num: 3
      min_free_mem_ratio: 0.1
      use_cuda_preproces: true
  number_classifier:
    enable: true
    model_path: ${ROOT_DIR}/model/mlp.onnx
    label_path: ${ROOT_DIR}/model/label.txt
  color_classifier:
    enable: true
    diff_threshold: 20.0

armor_tracker:
  lost_time_thres: 2.0
  tracking_thres: 10
  max_yaw_diff_deg: 60.0
  max_dis_diff: 3.0
  match_gate: 10.0
  qxyz_common: [20.0, 20.0, 1.0]
  qyaw_common: 10.0
  qxyz_output: [10.0, 10.0, 0.5]
  qyaw_output: 0.01
  q_r: 0.0000001
  q_l: 0.0000001
  q_h: 0.0000001
  q_outpost_dz: 0.5
  yp_r: 2e-3
  dis_r_front: 0.5
  dis_r_side: 2.5
  dis2_r_ratio: 0.1
  yaw_r_base_front: 0.2
  yaw_r_base_side: 0.06
  yaw_r_log_ratio: 0.02
  esekf_iter_num: 5

auto_aim_fsm:
  single_whole_up: 1.5 
  single_whole_down: 1.0
  whole_pair_up: 5.5 
  whole_pair_down: 3.5 #1s内至少换2次板子  2pi  否则轨迹规划无意义
  pair_center_up: 16.5
  pair_center_down: 15.0
  transfer_thresh: 50


very_aimer:
  sample_total_time: 2.0
  
  sample_horizon: 500

  control_delay: 0.1
  
  max_yaw_acc: 40
  #全向yaw加速度测算37
  max_pitch_acc: 50
  

  prediction_delay: 0.00
  comming_angle: 55
  leaving_angle: 20

  yaw_limit_deg: 60
  shooting_range_h: 0.12
  shooting_range_w_small: 0.12
  shooting_range_w_large: 0.24
  min_enable_pitch_deg: 0.25
  min_enable_yaw_deg: 0.25
  ballistic_trajectory:
    gravity: 9.8
    resistance: 0.092
    max_iter: 10
  